# Generated by Django 4.2.15 on 2024-08-30 15:22

from django.db import migrations, models
import django.db.models.deletion
import patients.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="NOME")),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        validators=[patients.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "rg_number",
                    models.CharField(blank=True, max_length=20, verbose_name="RG Nº"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ORGÃO EXPEDIDOR"
                    ),
                ),
                ("date_birth", models.DateField(verbose_name="NASCIDO EM")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "MASCULINO"), ("F", "FEMININO")],
                        max_length=1,
                        verbose_name="SEXO",
                    ),
                ),
                (
                    "place_birth",
                    models.CharField(max_length=100, verbose_name="NATURALIDADE"),
                ),
                (
                    "country_birth",
                    models.CharField(max_length=100, verbose_name="NACIONALIDADE"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("ST", "SOLTEIRO"),
                            ("CS", "CASADO"),
                            ("SP", "SEPARADO"),
                            ("DV", "DIVORCIADO"),
                            ("VV", "VIUVO"),
                        ],
                        max_length=2,
                        verbose_name="ESTADO CIVIL",
                    ),
                ),
                (
                    "current_job",
                    models.CharField(max_length=100, verbose_name="PROFISSÃO"),
                ),
                (
                    "health_plan",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="PLANO DE SAÚDE"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, verbose_name="OBSERVAÇÕES"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="CRIADO EM"),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[patients.validators.validate_phone],
                        verbose_name="TELEFONE 1",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[patients.validators.validate_phone],
                        verbose_name="TELEFONE 2",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="EMAIL"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patients",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="ENDEREÇO")),
                (
                    "address_number",
                    models.CharField(max_length=10, verbose_name="NÚMERO"),
                ),
                (
                    "address_district",
                    models.CharField(max_length=255, verbose_name="BAIRRO"),
                ),
                (
                    "address_city",
                    models.CharField(max_length=255, verbose_name="CIDADE"),
                ),
                (
                    "address_state",
                    models.CharField(
                        choices=[["MT", "Mato Grosso"]],
                        max_length=2,
                        verbose_name="ESTADO",
                    ),
                ),
                (
                    "address_complement",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="COMPLEMENTO"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patients",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
    ]
