# Generated by Django 4.2.15 on 2024-09-25 18:37

from django.db import migrations, models
import django.db.models.deletion
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('scheduling_cpf', models.CharField(max_length=14, validators=[patients.validators.validate_cpf], verbose_name='CPF')),
                ('patient_name', models.CharField(default='Sem Cadastro', max_length=255, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Término')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patients', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.DeleteModel(
            name='Scheduling',
        ),
    ]
