# Generated by Django 4.2.15 on 2024-10-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NOME')),
                ('specialty', models.CharField(max_length=255, verbose_name='ESPECIALIDADE')),
                ('cro', models.CharField(max_length=15, verbose_name='CRO')),
            ],
            options={
                'verbose_name': 'Doutor',
                'verbose_name_plural': 'Doutores',
            },
        ),
    ]
