# Generated by Django 4.2.15 on 2024-09-10 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctors",
            options={"verbose_name": "Doutor", "verbose_name_plural": "Doutores"},
        ),
    ]
